//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waito
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitoRecipe
    {
        public int RecipeID { get; set; }
        public string Title { get; set; }
        public string Ingredients { get; set; }
        public string Serves { get; set; }
        public string Description { get; set; }
        public string LargeImage { get; set; }
        public string MediumImage { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
